<?php 

?>
<span> Custom Price Range </span>
<div id="formarea">

   <form id="pricerange" name="pricerange" method="post">
      <input type="number" id="lowrange" name="lowrange" min="0" value="0" data-validate="{required:true}" placeholder="Low Range">
      <input type="number" id="highrange" name="highrange" min="0" value="0" data-validate="{required:true}" placeholder="High Range">
      <select name="sortbyprice" id="sortbyprice">
         <option value="A">Ascending</option>
         <option value="D">Descending</option>
      </select>
      <input type="submit">
   </form>
</div>


<div id="catalogarea">
   <?php
   
   $collection = $block->getProductCollection();
         
foreach ($collection as $_product) {
    echo $_product->getThumbnail()  . ' - ' . $_product->getSku() . ' - ' . $_product->getName() . ' - ' . $_product->getQty()  . ' - ' . $_product->getPrice() . ' - ' . $_product->getProductUrl() . '<br />';
}

         

    ?>
</div>


<script>
   $(document).ready(function() {
      $("#pricerange").submit(function() {

         var dataForm = $('#pricerange');
         dataForm.mage('validation', {});

         var lowrange = dataForm.find('input[name="lowrange"]').val();
         var highrange = dataForm.find('input[name="highrange"]').val();


         if ((highrange >= lowrange) && (highrange <= (lowrange * 5))) {

            jQuery.ajax({
               url: "/custpricerange/customer/index",
               type: "POST",
               data: {
                  lowrange: lowrange,
                  highrange: highrange,
                  sortbyprice: sortbyprice
               },
               success: function(response) {
                  console.log(response);
               }
            })
         } else {
            return false;
         };
      });
   });

</script>
